
const ci1=document.querySelector(".ci1")
const ci2=document.querySelector(".ci2")
const ci3=document.querySelector(".ci3")
const ci4=document.querySelector(".ci4")
const ci5=document.querySelector(".ci5")
const ci6=document.querySelector(".ci6")
const ci7=document.querySelector(".ci7")
const ci8=document.querySelector(".ci8")

const ws1=document.querySelector(".ws1")
const ws2=document.querySelector(".ws2")
const ws3=document.querySelector(".ws3")
const ws4=document.querySelector(".ws4")
const ws5=document.querySelector(".ws5")
const ws6=document.querySelector(".ws6")
const ws7=document.querySelector(".ws7")
const ws8=document.querySelector(".ws8")

const wsp=document.querySelector(".wsp")

ws1.addEventListener("click",()=>{
    ci1.classList.add("active")
    ci2.classList.remove("active")
    ci3.classList.remove("active")
    ci4.classList.remove("active")
    ci5.classList.remove("active")
    ci6.classList.remove("active")
    ci7.classList.remove("active")
    ci8.classList.remove("active")

})
ws2.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.add("active")
    ci3.classList.remove("active")
    ci4.classList.remove("active")
    ci5.classList.remove("active")
    ci6.classList.remove("active")
    ci7.classList.remove("active")
    ci8.classList.remove("active")

})
ws3.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.remove("active")
    ci3.classList.add("active")
    ci4.classList.remove("active")
    ci5.classList.remove("active")
    ci6.classList.remove("active")
    ci7.classList.remove("active")
    ci8.classList.remove("active")

})
ws4.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.remove("active")
    ci3.classList.remove("active")
    ci4.classList.add("active")
    ci5.classList.remove("active")
    ci6.classList.remove("active")
    ci7.classList.remove("active")
    ci8.classList.remove("active")

})
ws5.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.remove("active")
    ci3.classList.remove("active")
    ci4.classList.remove("active")
    ci5.classList.add("active")
    ci6.classList.remove("active")
    ci7.classList.remove("active")
    ci8.classList.remove("active")

})
ws6.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.remove("active")
    ci3.classList.remove("active")
    ci4.classList.remove("active")
    ci5.classList.remove("active")
    ci6.classList.add("active")
    ci7.classList.remove("active")
    ci8.classList.remove("active")

})
ws7.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.remove("active")
    ci3.classList.remove("active")
    ci4.classList.remove("active")
    ci5.classList.remove("active")
    ci6.classList.remove("active")
    ci7.classList.add("active")
    ci8.classList.remove("active")

})
ws8.addEventListener("click",()=>{
    ci1.classList.remove("active")
    ci2.classList.remove("active")
    ci3.classList.remove("active")
    ci4.classList.remove("active")
    ci5.classList.remove("active")
    ci6.classList.remove("active")
    ci7.classList.remove("active")
    ci8.classList.add("active")

})
